import os

VERSION = 1.0
SPLASH_WELCOME = f"Welcome to PyPass {VERSION}! An interactive password manager."
SPLASH_COPYRIGHT = "Copyright 2021 Youngwoo Kim."
SPLASH_TIP = "Enter 'help' to see the list of available commands."

# PATHS TO DIRECTORIES, FILES
PATH_DATADIR = 'data'

NAME_KEYFILE = 'master.key'
NAME_SALTFILE = 'master.salt'
NAME_DBFILE = 'credentials.db'
NAME_DBFILE_ENC = 'credentials.db.enc'
NAME_MASTER_USERNAMEFILE = 'uname'
NAME_MASTER_USERNAMEFILE_ENC = 'uname.enc'

PATH_KEYFILE = os.path.join(PATH_DATADIR, NAME_KEYFILE)
PATH_SALTFILE = os.path.join(PATH_DATADIR, NAME_SALTFILE)
PATH_DBFILE = os.path.join(PATH_DATADIR, NAME_DBFILE)
PATH_DBFILE_ENC = os.path.join(PATH_DATADIR, NAME_DBFILE_ENC)
PATH_MASTER_USERNAMEFILE = os.path.join(PATH_DATADIR, NAME_MASTER_USERNAMEFILE)
PATH_MASTER_USERNAMEFILE_ENC = os.path.join(PATH_DATADIR, NAME_MASTER_USERNAMEFILE_ENC)

# PARAMETERS
SCRYPT_R = 8
SCRYPT_N = 2 ** 15
SCRYPT_P = 1
SCRYPT_MAX_MEM = 64 * 2 ** 20
SCRYPT_DKLEN = 32

MASTER_PW_MAX_ATTEMPTS = 5
MASTER_PW_MIN_LEN = 6
MASTER_USERNAME_MIN_LEN = 3

SERVICE_NAME_MAX_LEN = 512
USER_ID_MAX_LEN = 512
USER_PW_MIN_LEN = 6

SEARCH_QUERY_MIN_LEN = 3
SEARCH_QUERY_MAX_LEN = 512